import React, { useState } from 'react';

function About() {
  // State to keep track of the active slide
  const [activeSlide, setActiveSlide] = useState(1);

  // Function to handle click on the slider buttons
  const handleSlideClick = (slideNumber) => {
    setActiveSlide(slideNumber);
  };

  // Function to navigate to the previous slide
  const previousSlide = () => {
    if (activeSlide === 1) {
      setActiveSlide(slidesContent.length);
    } else {
      setActiveSlide(activeSlide - 1);
    }
  };

  // Function to navigate to the next slide
  const nextSlide = () => {
    if (activeSlide === slidesContent.length) {
      setActiveSlide(1);
    } else {
      setActiveSlide(activeSlide + 1);
    }
  };

  // Content for each slide
  const slidesContent = [
    {
      heading: "About Us",
      description1: "We aim to develop cutting-edge technology that",
      description2: "enhances treatment planning through real-time simulation.",
      description3: "We employ neural operator learning to create",
      description4: "deep learning-based models specifically tailored",
      description5: "for radio-frequency (RFA) simulation."
    },
    {
      subheading1: "Neural Operator Learning",
      description6: "Employ neural operator learning to construct a",
      description7: "deep learning based model",
      subheading2: "Radiofrequency Ablation",
      description8: "Use heat generated by high frequency electrical current",
      description9: "to treat small liver tumours",
    },
    // Add more slides as needed
    {
      description11: "Leading institutions",
      description12: "Medical Professionals",
      description13: "Researchers",
    },
    {
      // Add content for the 4th slide
    },
  ];

  return (
    <div className="relative h-screen">
      {/* Background */}
      <video autoPlay loop muted className="absolute inset-0 w-full h-full object-cover z-0">
        <source src="aboutbg.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>

      {/* Overlay */}
      <div className="absolute inset-0 bg-black opacity-50"></div>

      {/* Content */}
      <div className="flex flex-col lg:flex-row items-center justify-center absolute inset-0">
        {/* Left side */}
        <div className="p-8 bg-transparent z-10">
          {slidesContent[activeSlide - 1].heading && <h1 className="text-white text-4xl lg:text-5xl font-bold">{slidesContent[activeSlide - 1].heading}</h1>}
        </div>

        {/* Middle space */}
        <div className="p-5 lg:p-20"></div>

        {/* Right side */}
        <div className="p-10 bg-transparent z-10">
          <div className="text-white">
            <div className="flex flex-col mb-8">
              <p className="text-base lg:text-lg p-2">{slidesContent[activeSlide - 1].description1}</p>
              <p className="text-base lg:text-lg p-2">{slidesContent[activeSlide - 1].description2}</p>
              <br />
              <p className="text-base lg:text-lg p-2 mt-10">{slidesContent[activeSlide - 1].description3}</p>
              <p className="text-base lg:text-lg p-2">{slidesContent[activeSlide - 1].description4}</p>
              <p className="text-base lg:text-lg p-2">{slidesContent[activeSlide - 1].description5}</p>
            </div>
          </div>
        </div>
      </div>

      {activeSlide === 2 && (
        <div>
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="max-w-screen-xl w-full flex justify-center">
              {/* Heading */}
              <div className="flex flex-col items-center justify-center w-full">
                <h1 className="text-white text-3xl md:text-3xl lg:text-4xl font-bold pb-10">Technology and Medicine</h1>
                {/* Vertical line */}
                <div className="mt-5 w-0.5 h-80 bg-white"></div> {/* Adjusted height to h-80 */}
              </div>
            </div>
          </div>

          <div className="absolute inset-0 flex items-center justify-center">
            <div className="max-w-screen-xl w-full flex justify-center">
              {/* Left side */}
              <div className="flex flex-col items-center justify-center w-full md:w-1/2 pr-4"> {/* Adjusted width to full width on small screens */}
                <div className="pl-4 pt-5">
                  <p className="text-base md:text-lg lg:text-xl xl:text-2xl p-2 text-center font-semibold pt-8 pb-8">{slidesContent[activeSlide - 1].subheading1}</p>

                  {/* Icon with description */}
                  <div className="flex items-center justify-center">
                    <img src="neuralnetwork.png" alt="Neural Networks Icon" className="w-20 h-20" />
                    <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 ">{slidesContent[activeSlide - 1].description11}</p>
                  </div>

                  <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 text-center pt-8">{slidesContent[activeSlide - 1].description6}</p>
                  <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 text-center">{slidesContent[activeSlide - 1].description7}</p>
                </div>
              </div>

              {/* Right side */}
              <div className="flex flex-col items-center justify-center w-full md:w-1/2 pl-4"> {/* Adjusted width to full width on small screens */}
                <div className="pl-4 pt-5">
                  <p className="text-base md:text-lg lg:text-xl xl:text-2xl p-2 text-center font-semibold pt-8 pb-8">{slidesContent[activeSlide - 1].subheading2}</p>
                  <div className="flex items-center justify-center">
                    <img src="surgery.png" alt="Surgery Icon" className="w-20 h-20" />
                    <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 ">{slidesContent[activeSlide - 1].description11}</p>
                  </div>
                  <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 text-center pt-8">{slidesContent[activeSlide - 1].description8}</p>
                  <p className="text-xs md:text-sm lg:text-base xl:text-lg p-2 text-center">{slidesContent[activeSlide - 1].description9}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {activeSlide === 3 && (
        <div className="flex flex-col lg:flex-row items-center justify-center absolute inset-0">
          {/* Left side */}
          <div className="text-center p-8 bg-transparent z-10">
            <h1 className="text-white text-4xl md:text-4xl lg:text-5xl font-bold">Collaborations and</h1>
            <h1 className="text-white text-4xl md:text-4xl lg:text-5xl font-bold mt-2 md:mt-5">Partnerships</h1>
          </div>


          {/* Middle space */}
          <div className="p-5 lg:p-20"></div>

          {/* Right side */}
          <div className="p-10 bg-transparent z-10">
            <div className="text-white">
              <div className="flex flex-col mb-8">
                <div className="flex items-center">
                  <img src="school.png" alt="Leading Institutions Icon" className="w-16 h-16 lg:w-20 lg:h-20 mr-4 lg:mr-10" />
                  <p className="text-base lg:text-lg p-2 ml-2 lg:ml-10">{slidesContent[activeSlide - 1].description11}</p>
                </div>
                <div className="flex items-center mt-5 lg:mt-10">
                  <img src="care.png" alt="Medical Professionals Icon" className="w-16 h-16 lg:w-20 lg:h-20 mr-4 lg:mr-10" />
                  <p className="text-base lg:text-lg p-2 ml-2 lg:ml-10">{slidesContent[activeSlide - 1].description12}</p>
                </div>
                <div className="flex items-center mt-5 lg:mt-10">
                  <img src="research.png" alt="Researchers Icon" className="w-16 h-16 lg:w-20 lg:h-20 mr-4 lg:mr-10" />
                  <p className="text-base lg:text-lg p-2 ml-2 lg:ml-10">{slidesContent[activeSlide - 1].description13}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {activeSlide === 4 && (
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <h1 className="text-white text-4xl md:text-6xl lg:text-7xl font-bold">Join Us in the Fight</h1>
          <h1 className="text-white text-4xl md:text-6xl lg:text-7xl font-bold p-5 md:p-10 mb-5 md:mb-10">Against Liver Cancer</h1>
          <p className="text-sm md:text-base lg:text-lg xl:text-xl p-2 text-center">Explore our vision for the future of our project and our commitment</p>
          <p className="text-sm md:text-base lg:text-lg xl:text-xl p-2 text-center mt-2">to continued growth and improvement.</p>
        </div>
      )}

      {/* Slider Buttons */}
      <div className="absolute bottom-0 py-4 flex justify-center gap-3 w-full z-10">
        {slidesContent.map((_, index) => (
          <button
            key={index + 1}
            className={`rounded-full w-5 h-5 cursor-pointer ${activeSlide === index + 1 ? 'bg-violet-500' : 'bg-white'}`}
            onClick={() => handleSlideClick(index + 1)}
          ></button>
        ))}
      </div>

      {/* Previous Slide Button */}
      <div className="absolute top-0 h-full w-full justify-between items-center flex text-white px-10 text-3xl z-10">
        <button onClick={previousSlide}>
          {/* Left Arrow SVG */}
          <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M5.646 10l4.524-4.524a.5.5 0 0 1 .854.353v8.342a.5.5 0 0 1-.854.354L5.646 10z" clipRule="evenodd" />
          </svg>
        </button>
        {/* Next Slide Button */}
        <button onClick={nextSlide}>
          {/* Right Arrow SVG */}
          <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M14.354 10l-4.524 4.524a.5.5 0 0 1-.854-.353V5.823a.5.5 0 0 1 .854-.353L14.354 10z" clipRule="evenodd" />
          </svg>
        </button>
      </div>
    </div>
  );
}

export default About;
